language: python

sudo: false

install:
    pip install tox

script: tox

matrix:
  include:
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=py37
      dist: xenial
      sudo: required
      python: 3.7
    - env: TOXENV=py38
      dist: xenial
      sudo: required
      python: 3.8-dev
    - env: TOXENV=pypy
      python: pypy
    - env: TOXENV=py27-flake8
      python: 2.7
    - env: TOXENV=py37-flake8
      dist: xenial
      sudo: required
      python: 3.7
